apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: ${CLUSTER_CLASS_NAME}
  namespace: default
spec:
  controlPlane:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: GCPManagedControlPlaneTemplate
      name: ${CLUSTER_NAME}-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: GCPManagedClusterTemplate
      name: ${CLUSTER_NAME}
  workers:
    machinePools:
    - class: default-system
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: GKEConfigTemplate
            name: ${CLUSTER_NAME}-pool0
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: GCPManagedMachinePoolTemplate
            name: ${CLUSTER_NAME}-pool0
    - class: default-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: GKEConfigTemplate
            name: ${CLUSTER_NAME}-pool1
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: GCPManagedMachinePoolTemplate
            name: ${CLUSTER_NAME}-pool1
---
kind: GCPManagedControlPlaneTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  template:
    spec:
      project: "${GCP_PROJECT}"
      location: "${GCP_REGION}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedClusterTemplate
metadata:
  name: ${CLUSTER_NAME}
spec:
  template:
    spec:
      project: "${GCP_PROJECT}"
      region: "${GCP_REGION}"
      network:
        name: "${GCP_NETWORK_NAME}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedMachinePoolTemplate
metadata:
  name: ${CLUSTER_NAME}-pool0
  namespace: default
spec:
  template:
    spec:
      nodePoolName: ${CLUSTER_NAME}-pool0
      nodeLocations:
        - "${GCP_REGION}-a"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedMachinePoolTemplate
metadata:
  name: ${CLUSTER_NAME}-pool1
  namespace: default
spec:
  template:
    spec:
      nodePoolName: ${CLUSTER_NAME}-pool1
      nodeLocations:
        - "${GCP_REGION}-a"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: GKEConfigTemplate
metadata:
  name: ${CLUSTER_NAME}-pool0
  namespace: default
spec:
  template:
    spec: {}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: GKEConfigTemplate
metadata:
  name: ${CLUSTER_NAME}-pool1
  namespace: default
spec:
  template:
    spec: {}
