---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  topology:
    class: ${CLUSTER_CLASS_NAME}
    version: ${KUBERNETES_VERSION}
    variables:
    - name: region
      value: ${GCP_REGION}
    - name: networkName
      value: ${GCP_NETWORK_NAME}
