# Check for broken links
name: Link-check

on:
  push:
    paths:
      - "docs/**"
    branches:
      - main
  pull_request:
    paths: "docs/**"

permissions: {}

jobs:
  lint_docs:
    name: Broken Links
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - uses: gaurav-nelson/github-action-markdown-link-check@3c3b66f1f7d0900e37b71eca45b63ea9eedfce31 # v1.0.17
      with:
        use-quiet-mode: 'yes'
        config-file: ".markdownlinkcheck.json"
